! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use collective_subroutines_test, only: &
                collective_subroutines_co_all => test_co_all, &
                collective_subroutines_co_sum => test_co_sum
        use data_partition_test, only: &
                data_partition_data_partition => test_data_partition
        use object_interface_test, only: &
                object_interface_object => test_object
        use single_image_intrinsics_test, only: &
                single_image_intrinsics_findloc => test_findloc
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(5)

        individual_tests(1) = collective_subroutines_co_all()
        individual_tests(2) = collective_subroutines_co_sum()
        individual_tests(3) = data_partition_data_partition()
        individual_tests(4) = object_interface_object()
        individual_tests(5) = single_image_intrinsics_findloc()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
