! Generated by make_vegetable_driver. DO NOT EDIT
program main
    implicit none

    call run()
contains
    subroutine run()
        use data_partition_test, only: &
                data_partition_data_partition => &
                    test_data_partition
        use vegetables, only: test_item_t, test_that, run_tests



        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = data_partition_data_partition()
        tests = test_that(individual_tests)


        call run_tests(tests)

    end subroutine
end program
