as_character –
as_character Interface
126 statements
Source File
interface
Called by
private pure module function as_character(self) result(raw_string) Implementation →
Arguments
Type Intent Optional Attributes Name
class(string_t), intent(in) :: self
Return Value character(len=:),allocatable
Call graph
assign_string_t_to_character calls string
base_name calls string
character_eq_string_t calls string
character_ne_string_t calls string
characterize calls string
concatenate_elements calls string
contains_text calls string
description_contains calls string
file_extension calls string
get_json_integer calls string
get_json_key calls string
get_json_logical calls string
get_json_real calls string
get_json_real_array calls string
get_json_string calls string
read_lines calls string
string_t_eq_character calls string
string_t_eq_string_t calls string
string_t_ne_character calls string
string_t_ne_string_t calls string
write_lines calls string