concatenate_rows –
concatenate_rows Interface
17 statements
Source File
interface
Calls
Called by
private pure module module function concatenate_rows(a, b) result(concatenated) Implementation →
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:,:) :: a
real, intent(in), dimension(:,:) :: b
Return Value real,dimension(:,:),allocatable
Description
Result contains the concatenation of the rows of argument a with the rows of argument b
Call graph
concatenate_rows calls concatenate_rows, concatenate_columns
concatenate_columns calls concatenate_columns, assert
operator(.catrows.) calls concatenate_rows