operator(.catRows.) –
operator(.catRows.) Interface
3 statements
Source File
public interface operator(.catRows.)
Calls
Contents
Module Procedures
concatenate_rows
Module Procedures
private interface concatenate_rows()
Arguments
None
Call graph
operator(.catrows.) calls concatenate_rows
concatenate_rows calls concatenate_rows, concatenate_columns
concatenate_columns calls concatenate_columns, assert