report –
report Interface
7 statements
Source File
interface
Calls
private module module subroutine report(test, passes, tests) Implementation →
Arguments
Type Intent Optional Attributes Name
class(test_t), intent(in) :: test
integer, intent(inout) :: passes
integer, intent(inout) :: tests
Description
Print the test results and increment the tallies of passing tests and total tests
Call graph
report calls report, test_results, co_all, passing_tests
co_all calls co_all