string_t –
string_t Interface
17 statements
Source File
public interface string_t
Called by
Contents
Functions
construct from_default_integer from_real
Functions
private elemental module function construct(string) result(new_string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value type(string_t)
private elemental module function from_default_integer(i) result(string)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Return Value type(string_t)
private elemental module function from_real(x) result(string)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value type(string_t)
Call graph
array_of_strings calls string_t, array_of_strings
character_cat_string_t calls string_t, character_cat_string_t
from_real calls string_t
get_json_key calls string_t, get_json_key
string_t_cat_character calls string_t, string_t_cat_character
get_json_string calls string_t, get_json_string
string_t_cat_string_t calls string_t, string_t_cat_string_t
from_default_integer calls string_t